### ISSUE TITLE
[FEATURE] Redesign the Login Page

### ISSUE THREAD

**Issue by sahilsaha7773** [sahilsaha7773/SpotLight#1]
Redesign the Login Page UI (`/login`)  and make it responsive.

## Login Page Screenshot
![Screenshot from 2022-01-21 14-25-13](https://user-images.githubusercontent.com/35343652/150496991-d083495f-51de-44b5-a106-5cba377687b0.png)

**Comment by 19082002** [comment]
I want to work in this issue.

**Comment by Ambareen09** [comment]
I'm interested to work on this

**Comment by 19082002** [comment]
I want to work in this issue under JWOC.

**Comment by sahilsaha7773** [comment]
@19082002 assigned!
