### ISSUE TITLE
[FEATURE] Currently Playing 

### ISSUE THREAD

**Issue by sahilsaha7773** [sahilsaha7773/SpotLight#10]
Use the Spotify API to get details about the user's currently playing song and show it on the home page.

**Comment by aritrasen12345** [comment]
I can try this. Assign this feature to me.

**Comment by sahilsaha7773** [comment]
> I can try this. Assign this feature to me.

Hey @aritrasen12345! Have you registered in JWOC? If you have, please wait for the coding period to begin, or else you can register here https://jwoc.tech

**Comment by varunwho** [comment]
@sahilsaha7773 can I try working on this under JWOC?

**Comment by sahilsaha7773** [comment]
@varunwho assigned!

**Comment by varunwho** [comment]
I'm actually stuck up with some urgent stuff, so I'll unassign myself. Sorry! And thanks for the chance!

**Comment by sahilsaha7773** [comment]
@03amir assigned!

**Comment by aritrasen12345** [comment]
I also want to work on this issue under JWOC.
