### ISSUE TITLE
[FEATURE] Create a NavBar

### ISSUE THREAD

**Issue by sahilsaha7773** [sahilsaha7773/SpotLight#2]
Create a top NavBar component, it should have the following:
- A functional `Logout` button.
- Brand name `SpotLight`.
- Profile Icon.

Suggestions are welcomed :smiley:.

**Comment by 19082002** [comment]
I want to work in this issue.

**Comment by lavakush07** [comment]
"I want to work on this issue under JWOC"

**Comment by sahilsaha7773** [comment]
@lavakush07 assigned!

**Comment by lavakush07** [comment]
> @lavakush07 assigned!
@sahilsaha7773  Thank u..

**Comment by adityarathore063** [comment]
i want to work on this issue

**Comment by sahilsaha7773** [comment]
@lavakush07 am unassigning you as there's no update from your side

**Comment by sahilsaha7773** [comment]
@adityarathore063 assigned!

**Comment by adityarathore063** [comment]
> @adityarathore063 assigned!
Thanks for assigning this issue @sahilsaha7773

**Comment by 03amir** [comment]
I want to work on this issue under JWOC"

**Comment by sahilsaha7773** [comment]
@adityarathore063 as there's no update from ur side am assigning it to @03amir

**Comment by Aniket-508** [comment]
@sahilsaha7773 I want to work on this issue under JWoC.
