### ISSUE TITLE
[FEATURE] Add Link in "Top Artists" section

### ISSUE THREAD

**Issue by sahilsaha7773** [sahilsaha7773/SpotLight#3]
Each artist card in the "Top Artists" section should open the Spotify artist page on click. You can get the links from the data received in the top artists API response.

## Artist Card Screenshot
![Screenshot from 2022-01-21 15-06-02](https://user-images.githubusercontent.com/35343652/150503329-387b7415-f8f2-472e-a027-ca8e858d3e82.png)

**Comment by fakoredeDamilola** [comment]
Can I try this

**Comment by sahilsaha7773** [comment]
> Can I try this

Hi @fakoredeDamilola! This repo is participating in an open-source event https://jwoc.tech, please register for the even to contribute!

**Comment by firtysh** [comment]
I want to work on this issue under JWOC.

**Comment by sahilsaha7773** [comment]
@firtysh assigned!

**Comment by raxvab** [comment]
I want to work with this issue under JWOC
