### ISSUE TITLE
[FEATURE] Show Artist Popularity

### ISSUE THREAD

**Issue by sahilsaha7773** [sahilsaha7773/SpotLight#4]
The response data from the top artists Spotify API has the popularity for each artist. Use that data to display the artist popularity in the artist cards.

## Artist Card Screenshot
![Screenshot from 2022-01-21 15-06-02](https://user-images.githubusercontent.com/35343652/150504164-e22e4647-2e1f-4f07-978f-130b0707dde4.png)

**Comment by maneeshc1497** [comment]
Hey @sahilsaha7773 I cannot login to the Application, It says INVALID_CLIENT: Failed to get client
Tried creating new account , same issue.

**Comment by sahilsaha7773** [comment]
> Hey @sahilsaha7773 I cannot login to the Application, It says INVALID_CLIENT: Failed to get client Tried creating new account , same issue.

Hi @maneeshc1497! Have you created the `.env.local` file?

**Comment by firtysh** [comment]
I want to work on this issue under JWOC.

**Comment by sahilsaha7773** [comment]
@firtysh assigned!

**Comment by raxvab** [comment]
Could you please add an assigned label.
