### ISSUE TITLE
[FEATURE] Add Page titile

### ISSUE THREAD

**Issue by sahilsaha7773** [sahilsaha7773/SpotLight#5]
Currently, the title of the website is the default `React App`, change the title to `Home | SpotLight` for the Home Page and `Login | SpotLight` for the Login Page.

**Comment by AbdirahimAhmedNor** [comment]
Would you mine if `I do that for you` ?

**Comment by Amornath** [comment]
@sahilsaha7773   I have changed the title of pages you have mention about. Can you check it? if you want.

**Comment by Sathasivamthirumoorthi** [comment]
Since , I am new to open source , I would like to work on this .

**Comment by sahilsaha7773** [comment]
> Since , I am new to open source , I would like to work on this .
Hey @Sathasivamthirumoorthi! Have you registered in JWOC? If you have, please wait for the coding period to begin, or else you can register here https://jwoc.tech

**Comment by valanm22** [comment]
I want to work on this issue under JWOC

**Comment by sahilsaha7773** [comment]
@valanm22 assigned!

**Comment by raxvab** [comment]
I want to work on this issue under JWOC
