### ISSUE TITLE
[FEATURE] Create a seperate Profile Page

### ISSUE THREAD

**Issue by sahilsaha7773** [sahilsaha7773/SpotLight#6]
Create a separate profile page at the `/profile` route. It should contain the details of the logged-in user, such as name, profile photos, country etc. 
The user data can be fetched from the Spotify web API (https://developer.spotify.com/documentation/web-api/reference/#/operations/get-current-users-profile).

**Comment by 03amir** [comment]
I want to work on this issue under JWOC

**Comment by sahilsaha7773** [comment]
@03amir assigned!
