### ISSUE TITLE
[FEATURE] Design a Logo

### ISSUE THREAD

**Issue by sahilsaha7773** [sahilsaha7773/SpotLight#7]
Design a logo/icon for `SpotLight` to display on the web page.

**Comment by Ambareen09** [comment]
I'm interested to work on this

**Comment by lavakush07** [comment]
"I want to work on this issue under JWOC"

**Comment by sahilsaha7773** [comment]
@lavakush07 assigned!

**Comment by raxvab** [comment]
I want to work on this issue under JWOC.

**Comment by lavakush07** [comment]
I have created the logo 
[logo.zip](https://github.com/sahilsaha7773/SpotLight/files/7976159/logo.zip)

**Comment by sahilsaha7773** [comment]
> I have created the logo [logo.zip](https://github.com/sahilsaha7773/SpotLight/files/7976159/logo.zip)

Can you make something that relates to Spotify and matches more with the purpose of the site?

**Comment by raxvab** [comment]
Can I try making one under JWOC ?

**Comment by lavakush07** [comment]
> > I have created the logo [logo.zip](https://github.com/sahilsaha7773/SpotLight/files/7976159/logo.zip)
> 
> Can you make something that relates to Spotify and matches more with the purpose of the site?

Yeah sure..

**Comment by sahilsaha7773** [comment]
@lavakush07 as there's no update, am assigning this to @raxvab

**Comment by raxvab** [comment]
.....................................

Vaibhav would like to stay in touch on LinkedIn.

Vaibhav Shukla
Pre Final year Student at IET LUCKNOW || JWOC'22 - OPEN SOURCE || JS & SQL || MERN || Data Structures and Algorithms || 4 🌟 CODECHEF (1815) || Hashcode 2712
India

View profile https://www.linkedin.com/comm/in/whyybhav?trk=eml-guest-invite-pprofile-link-cta&trkEmail=eml-email_m2g_invite_single_01-null-373-null-null-%7E3i324s%7El325jrpq%7E16-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3Bvdi%2FIRFgTT6veYE38Fe1%2Fw%3D%3D

Confirm that you know Vaibhav https://www.linkedin.com/e/v2?e=-3i324s-l325jrpq-16&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3Bvdi%2FIRFgTT6veYE38Fe1%2Fw%3D%3D&t=suwj&tracking=eml-guest-invite-cta&ek=email_m2g_invite_single_01&validationToken=k3NelYp4&invitationId=6930282115343228928


.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=-3i324s-l325jrpq-16&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_m2g_invite_single_01&li=381&m=unsub&ts=unsub&loid=AQGkrU-HF4JXBQAAAYC1O_NQd8XE-QSXmYne0NGsxjs1V6Edq9iI0ZfRAwSwQCOi-SfeLVb-HzKuE0CTSJW-zKXVwpPz-GISQ9mu3HXOJ0WWDjF49cKDDtZ5Urd1GYkTUSOnSeBRAVy28Hq4RDRKgwqVWuJMF5Yi2A&eid=-3i324s-l325jrpq-16

Help: https://www.linkedin.com/e/v2?e=-3i324s-l325jrpq-16&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3Bvdi%2FIRFgTT6veYE38Fe1%2Fw%3D%3D&a=customerServiceUrl&ek=email_m2g_invite_single_01&li=380&m=footer&ts=help&articleId=67


You are receiving Invitation emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to ***@***.***

© 2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by raxvab** [comment]
Hi ,

Vaibhav would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-3i324s-l3c17tef-no&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3BixKEvDeUSWS25bg4YUheLg%3D%3D&t=suwj&ek=email_first_guest_reminder_03&li=20&m=hero&ts=accept_text

View Vaibhav’s profile: https://www.linkedin.com/comm/in/whyybhav?trk=eml-email_first_guest_reminder_03-hero-2-prof%7Ename&trkEmail=eml-email_first_guest_reminder_03-hero-2-prof%7Ename-null-%7E3i324s%7El3c17tef%7Eno-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3BixKEvDeUSWS25bg4YUheLg%3D%3D



.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=-3i324s-l3c17tef-no&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_first_guest_reminder_03&li=17&m=unsub&ts=unsub&loid=AQEBQi_PADEOtQAAAYDY11JK-1PaItMVagQymRKfPPM8Ckdm3pv93Chn4fOWeErmZxAtvnvBccG7pcKIAAIt1rcDlnILL8bTNS6WiaUF2-ZmByx344Cnumjxt3dZPa0ccvh9eRpFdxGnbxMIF2pnE5GsUNx5E7bwG2xZgw&eid=-3i324s-l3c17tef-no

Help: https://www.linkedin.com/e/v2?e=-3i324s-l3c17tef-no&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3BixKEvDeUSWS25bg4YUheLg%3D%3D&a=customerServiceUrl&ek=email_first_guest_reminder_03&li=16&m=footer&ts=help&articleId=67


 LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to ***@***.***

© 2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by raxvab** [comment]
https://www.linkedin.com/e/v2?e=-3i324s-l3m1cbna-9z&lipi=urn%3Ali%3Apage%3Aemail_email_second_guest_reminder_03%3B%2B44D5eKASI%2BscGf3jM6nHQ%3D%3D&t=suwj&ek=email_second_guest_reminder_03&li=11&m=hero&ts=accept_text

 https://www.linkedin.com/comm/in/whyybhav?trk=eml-email_second_guest_reminder_03-hero-2-prof%7Ename&trkEmail=eml-email_second_guest_reminder_03-hero-2-prof%7Ename-null-%7E3i324s%7El3m1cbna%7E9z-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_second_guest_reminder_03%3B%2B44D5eKASI%2BscGf3jM6nHQ%3D%3D



.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=-3i324s-l3m1cbna-9z&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_second_guest_reminder_03&li=8&m=unsub&ts=unsub&loid=AQHGxMYcP7gATwAAAYD85O91nll9IkZNm_aJrEMQzw5pwsLoFhFVySukjYYl7MHFJzK9HwTNIlqJAYCvDkJButt0LkUOYXg_A77CjRpl1XyZ3uRKm-BbWm6tMyCxzOlseg6ipZwk74nHSALgE6LRDer0LEjIvef3-O1GXA&eid=-3i324s-l3m1cbna-9z

Help: https://www.linkedin.com/e/v2?e=-3i324s-l3m1cbna-9z&lipi=urn%3Ali%3Apage%3Aemail_email_second_guest_reminder_03%3B%2B44D5eKASI%2BscGf3jM6nHQ%3D%3D&a=customerServiceUrl&ek=email_second_guest_reminder_03&li=7&m=footer&ts=help&articleId=67


You are receiving Invitation reminder email emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to ***@***.***

© 2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
