### ISSUE TITLE
[BUG] Home page is not responsive

### ISSUE THREAD

**Issue by sahilsaha7773** [sahilsaha7773/SpotLight#8]
Make the home page responsive for small and medium screen devices.

**Comment by Ambareen09** [comment]
I'm interested to work on this issue

**Comment by 03amir** [comment]
I want to work on this issue under JWOC

**Comment by sahilsaha7773** [comment]
@03amir assigned!

**Comment by Shruti025** [comment]
Can I work on this issue under JWOC?

**Comment by sahilsaha7773** [comment]
if @03amir doesn't open a PR today, I will assign it to you @Shruti025
