### ISSUE TITLE
[FEATURE] Design the Top Genres section

### ISSUE THREAD

**Issue by sahilsaha7773** [sahilsaha7773/SpotLight#9]
Design the Top Genres section and make it responsive.

**Comment by Tess-Vanta** [comment]
I want to work on this issue under JWOC

**Comment by sahilsaha7773** [comment]
@Tess-Vanta go for it, I have assigned it to you!

**Comment by Tess-Vanta** [comment]
@sahilsaha7773 Thanks!!
